### ISSUE TITLE
Extra Variable Definition

### ISSUE THREAD

**Issue by CJoh-NHD** [NewhavenDisplay/NHD-320240WG-Example#1]
https://github.com/NewhavenDisplay/NHD-320240WG-Example/blob/918c29cc0c5cf4c7f49101d9349d17d755cbee6a/NHD_320240WG-Example/NHD_320240WG-Example.ino#L576

Variable `j` is defined but not utilized in the `disp()` function.
Please remove variable `j` definition from this function.

**Comment by ZPal-NHD** [comment]
Fixed
